--EXERCICIO 1

CREATE TABLE CLIENTES
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	NOME VARCHAR(20),
	TELEFONE VARCHAR(11),
	ENDERECO VARCHAR(50),
)

--EXERCICIO 2
INSERT INTO CLIENTES (NOME, TELEFONE, ENDERECO) VALUES ('Vinicius Silva', '987654', 'Rua Girassol') 
INSERT INTO CLIENTES (NOME, TELEFONE, ENDERECO) VALUES ('Maria Antonia', '123456', 'Rua Rosas') 
INSERT INTO CLIENTES (NOME, TELEFONE, ENDERECO) VALUES ('Marcos Vinicius', '654123', 'Rua Itajai') 

--EXERCICO 3
SELECT * FROM CLIENTES

--EXERCICO 4
SELECT * FROM CLIENTES
WHERE ID = 1

--EXERCICIO 5
SELECT * FROM CLIENTES
WHERE NOME LIKE '%Silva%'

--EXERCICO 6
UPDATE CLIENTES
SET ENDERECO = 'Rua Lim�o'
WHERE ID = 3

SELECT * FROM CLIENTES
WHERE ID = 3

--EXERCICIO 7
DELETE CLIENTES
WHERE ID = 2

SELECT * FROM CLIENTES