CREATE TABLE FUNCIONARIOS
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	NOME VARCHAR(20),
	CARGO VARCHAR(20),
	TELEFONE1 VARCHAR(11),
	TELEFONE2 VARCHAR(11),
)

SELECT * FROM FUNCIONARIOS
--------------------------------------------------------------------------------------
CREATE TABLE FUNCIONARIO_1
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	NOME VARCHAR(20),
	CARGO VARCHAR(20),
)

CREATE TABLE TELEFONE_1
(
	ID INT REFERENCES FUNCIONARIO_1(ID) NOT NULL,
	TELEFONE VARCHAR(11) NOT NULL,
)

SELECT * FROM TELEFONE_1 
SELECT * FROM FUNCIONARIO_1
--------------------------------------------------------------------------------------

CREATE TABLE CARGO_2
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	CARGO VARCHAR(20),
)

CREATE TABLE FUNCIONARIO_2
(
	NOME VARCHAR(20),
	CARGO_ID INT REFERENCES CARGO_2(ID),
)

CREATE TABLE TELEFONE_2
(
	CARGO_ID INT REFERENCES CARGO_2(ID) NOT NULL,
	TELEFONE VARCHAR(11) NOT NULL,
)

ALTER TABLE TELEFONE_2 ADD PRIMARY KEY (ID, TELEFONE)


SELECT * FROM CARGO_2
SELECT * FROM TELEFONE_2
SELECT * FROM FUNCIONARIO_2